name: tangram2
channels:
- conda-forge
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_gnu
- binutils_impl_linux-64=2.43=h4bf12b8_5
- bzip2=1.0.8=h4bc722e_7
- ca-certificates=2025.6.15=hbd8a1cb_0
- cddlib=1!0.94m=h9202a9a_0
- conda-gcc-specs=15.1.0=hc55bae6_3
- gcc=15.1.0=h33e79ad_3
- gcc_impl_linux-64=15.1.0=h4393ad2_3
- gmp=6.3.0=hac33072_2
- kernel-headers_linux-64=3.10.0=he073ed8_18
- ld_impl_linux-64=2.43=h712a8e2_5
- libexpat=2.7.0=h5888daf_0
- libffi=3.4.6=h2dba641_1
- libgcc=15.1.0=h767d61c_3
- libgcc-devel_linux-64=15.1.0=h4c094af_103
- libgcc-ng=15.1.0=h69a702a_3
- libgomp=15.1.0=h767d61c_3
- liblzma=5.8.1=hb9d3cd8_2
- libnsl=2.0.1=hb9d3cd8_1
- libsanitizer=15.1.0=h97b714f_3
- libsqlite=3.50.1=h6cd9bfd_7
- libstdcxx=15.1.0=h8f9b012_3
- libstdcxx-ng=15.1.0=h4852527_3
- libuuid=2.38.1=h0b41bf4_0
- libxcrypt=4.4.36=hd590300_1
- libzlib=1.3.1=hb9d3cd8_2
- ncurses=6.5=h2d0b736_3
- openssl=3.5.0=h7b32b05_1
- pip=25.1.1=pyh8b19718_0
- python=3.11.13=h9e4cc4f_0_cpython
- readline=8.2=h8c095d6_2
- setuptools=80.9.0=pyhff2d567_0
- sysroot_linux-64=2.17=h0157908_18
- tk=8.6.13=noxft_hd72426e_102
- tzdata=2025b=h78e105d_0
- wheel=0.45.1=pyhd8ed1ab_1

