---

data:
  exp1:
    sp:
      path: '/gstore/data/resbioai/spacerangers/cci-explore/pipeline/example_data/qx_visified.h5ad'
    sc:
      path: '/gstore/data/resbioai/spacerangers/cci-explore/pipeline/example_data/qx_mappable.h5ad'

methods:
  exp1:
    - map_CeLEry

method_params:
  exp1:
    map_CeLEry:
      num_epochs_max: 5

preprocess:
  exp1:
    exp1:
      sp:
        CeLEry:
      sc:
        CeLEry:

metrics:
  exp1:
    map_CeLEry:
      map_rmse: spatial

