---

experiment1:
  data:
    X_to: path_to_spatial
    X_from: path_to_single_cell

  workflows:
    wf_1:
      preprocess:
        X_to:
          pp_met_1:
            key_1: val_1
            key_2: val_2
          pp_met_2:
            key_1: val_1
            key_2: val_2

      recipe:
        pp_met_1:
          key_1: val_1
          key_2: val_2
        pp_met_2:
          key_1: val_1
          key_2: val_2

  evaluation:
    T:
      metrics:
        metric_1:
          key_1: val_1
        metric_2:
          key_2: val_2
      data:
        path:
        adata_key:
      params:
        key_1: val_1
        key_2: val_2
