---

data:
  exp1:
    sp:
      path: '/gstore/data/resbioai/spacerangers/cci-explore/pipeline/example_data/qx_visified.h5ad'
    sc:
      path: '/gstore/data/resbioai/spacerangers/cci-explore/pipeline/example_data/qx_mappable.h5ad'

methods:
  exp1:
    - wf_hejin

method_params:
  exp1:
    wf_hejin:
      map_args:
        training_genes: []
        num_epochs: 2
      group_args:
        feature_name: 'abcc11'
        thres_x: 9


preprocess:
  exp1:
    sc:
      total_normalize:
        target_sum: 1e4
metrics:
  exp1:
    wf_hejin:
      dev_print:
