name: tangram2
channels:
- conda-forge
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- binutils_impl_linux-64=2.43
- bzip2=1.0.8
- ca-certificates=2025.6.15
- cddlib=1!0.94m
- conda-gcc-specs=15.1.0
- gcc=15.1.0
- gcc_impl_linux-64=15.1.0
- gmp=6.3.0
- kernel-headers_linux-64=3.10.0
- ld_impl_linux-64=2.43
- libexpat=2.7.0
- libffi=3.4.6
- libgcc=15.1.0
- libgcc-devel_linux-64=15.1.0
- libgcc-ng=15.1.0
- libgomp=15.1.0
- liblzma=5.8.1
- libnsl=2.0.1
- libsanitizer=15.1.0
- libsqlite=3.50.1
- libstdcxx=15.1.0
- libstdcxx-ng=15.1.0
- libuuid=2.38.1
- libxcrypt=4.4.36
- libzlib=1.3.1
- ncurses=6.5
- openssl=3.5.0
- pip=25.1.1
- python=3.11.13
- readline=8.2
- setuptools=80.9.0
- sysroot_linux-64=2.17
- tk=8.6.13
- tzdata=2025b
- wheel=0.45.1
