name: tangram2
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - cddlib=1!0.94m=h6d7a090_0
  - gmp=6.3.0=h7bae524_2
  - libcxx=20.1.7=ha82da77_0
  - libexpat=2.7.0=h286801f_0
  - libffi=3.4.6=h1da3d7d_1
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.50.2=h6fb428d_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.5.0=h81ee809_1
  - pip=25.1.1=pyh8b19718_0
  - python=3.11.13=hc22306f_0_cpython
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_2
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
    - tangram2==0.0.0
    - uv==0.7.17

prefix: "/Users/andera29/micromamba/envs/tangram2"
