---

data:
  exp1:
    sp:
      path: '/gstore/data/resbioai/tangram2_data/breast_cancer/spatial/ad_sp_CID44971.h5ad'
    sc:
      path: '/gstore/data/resbioai/tangram2_data/breast_cancer/single_cell/Wu_etal_2021_BRCA_scRNASeq/ad_sc.h5ad'

methods:
  exp1:
    - wf_hejin

method_params:
  exp1:
    wf_hejin:
      map_args:
        num_epochs: 1000
      group_args:
        feature_name: 'cd274'
        thres_x: 9


preprocess:
  exp1:
    sc:
      total_normalize:
        target_sum: 1e4
metrics:
  exp1:
    wf_hejin:
      dev_print:
